### ISSUE TITLE
Insert attachments in emacs

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#131] opened 2016-05-11 22:19 UTC
In emacs one can use `mail-add-attachment` to insert attachments in gnus, mu4e and probably other MUAs. This function inserts the following text in the email body:

```
<#part type="application/octet-stream" filename="~/attachment.zip" disposition=attachment>
<#/part>
```

If astroid could recognize attachments in this format, then it would not be necessary to develop a keyboard-driven file chooser.

**Comment by gauteh** [comment] 2016-05-12 06:48
Duplicate of #10. There needs to be an editor-universal way of doing this, that works with gvim as well.

**Comment by gauteh** [comment] 2016-05-12 06:50
Related to #99.

**Comment by gauteh** [comment] 2016-05-12 06:57
This is not a priority for me to implement, but I would support contributions. As mentioned, it needs to be a general format (maybe like in #10).

**Comment by mardukbp** [comment] 2016-05-12 08:14
Oops. Sorry. I searched for `attachment` not for `attach` and that is why I was not aware of #10.

gvim and emacs have a keyboard-driven way to navigate the filesystem and insert a file path. GUI editors use a file chooser like astroid currently does. I guess the only way that we can have keyboard-driven insertion of attachments independently of the editor used is providing the functionality in astroid.

**Comment by gauteh** [comment] 2016-05-12 08:16
I believe the GTK file chooser has keyboard accelerators as well, but I admit I don't really use them (except for searching). It would be great with a completely keyboard driven file chooser.

**Comment by gauteh** [comment] 2016-05-17 16:38
I am closing this, this is not a priority. If someone wants to implement a editor-generic solution I'd be happy to discuss it. It has to be a way that does not conflict with writing normal emails and is not too hard to maintain.

**Closed by gauteh** 2016-05-17 16:38 UTC
Labels: feature-request
