### ISSUE TITLE
Loading long threads is slow

### ISSUE THREAD

**Issue by aureooms** [gauteh/astroid#118] opened 2016-04-25 09:54 UTC
It takes more than 25 seconds to load a 45 messages long thread on my end-of-2011-MacBook. Why is loading long threads so slow?

**Comment by gauteh** [comment] 2016-04-25 10:08
Duplicate of #113, please try out: #114 with patched gmime. Instructions are in #114.

**Closed by gauteh** 2016-04-25 10:08 UTC
Labels: duplicate

**Comment by aureooms** [comment] 2016-04-25 10:23
Thanks!
